name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3

    steps:
      - uses: actions/checkout@v4.1.6
      - uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: ${{ toJSON(secrets) }}
          region: ${{ env.AWS_REGION }}

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'
      - run: chmod +x gradlew
      - run: |
          export CODEARTIFACT_USERNAME=aws
          export CODEARTIFACT_URL=https://patrimoine-sonic-008541141815.d.codeartifact.eu-west-3.amazonaws.com/maven/harena-patrimoine/
          export CODEARTIFACT_PASSWORD=$(aws codeartifact get-authorization-token --domain patrimoine-sonic --domain-owner 008541141815 --region eu-west-3 --query authorizationToken --output text)
          ./gradlew test



  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: chmod +x format.sh
      - run: ./format.sh && git diff --exit-code